// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Prodvana
{
    /// <summary>
    /// This resource allows you to manage a Prodvana [Release Channel](https://docs.prodvana.io/docs/prodvana-concepts#release-channel).
    /// 
    /// ## Import
    /// 
    /// ```sh
    ///  $ pulumi import prodvana:index/releaseChannel:ReleaseChannel example &lt;application name&gt;/&lt;release channel name&gt;
    /// ```
    /// </summary>
    [ProdvanaResourceType("prodvana:index/releaseChannel:ReleaseChannel")]
    public partial class ReleaseChannel : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Name of the Application this Release Channel belongs to
        /// </summary>
        [Output("application")]
        public Output<string> Application { get; private set; } = null!;

        /// <summary>
        /// Constant values for this release channel
        /// </summary>
        [Output("constants")]
        public Output<ImmutableArray<Outputs.ReleaseChannelConstant>> Constants { get; private set; } = null!;

        /// <summary>
        /// Feature Coming Soon
        /// </summary>
        [Output("convergenceProtections")]
        public Output<ImmutableArray<Outputs.ReleaseChannelConvergenceProtection>> ConvergenceProtections { get; private set; } = null!;

        /// <summary>
        /// Preconditions requiring manual approval before this release channel can be deployed
        /// </summary>
        [Output("manualApprovalPreconditions")]
        public Output<ImmutableArray<Outputs.ReleaseChannelManualApprovalPrecondition>> ManualApprovalPreconditions { get; private set; } = null!;

        /// <summary>
        /// Release Channel name
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Release Channel policy applied to all services
        /// </summary>
        [Output("policy")]
        public Output<Outputs.ReleaseChannelPolicy?> Policy { get; private set; } = null!;

        /// <summary>
        /// Protections applied this release channel
        /// </summary>
        [Output("protections")]
        public Output<ImmutableArray<Outputs.ReleaseChannelProtection>> Protections { get; private set; } = null!;

        /// <summary>
        /// Preconditions requiring other release channels to be stable before this release channel can be deployed
        /// </summary>
        [Output("releaseChannelStablePreconditions")]
        public Output<ImmutableArray<Outputs.ReleaseChannelReleaseChannelStablePrecondition>> ReleaseChannelStablePreconditions { get; private set; } = null!;

        /// <summary>
        /// Release Channel policy applied to all services
        /// </summary>
        [Output("runtimes")]
        public Output<ImmutableArray<Outputs.ReleaseChannelRuntime>> Runtimes { get; private set; } = null!;

        /// <summary>
        /// Protections applied to service instances in this release channel
        /// </summary>
        [Output("serviceInstanceProtections")]
        public Output<ImmutableArray<Outputs.ReleaseChannelServiceInstanceProtection>> ServiceInstanceProtections { get; private set; } = null!;

        /// <summary>
        /// Current application version
        /// </summary>
        [Output("version")]
        public Output<string> Version { get; private set; } = null!;


        /// <summary>
        /// Create a ReleaseChannel resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public ReleaseChannel(string name, ReleaseChannelArgs args, CustomResourceOptions? options = null)
            : base("prodvana:index/releaseChannel:ReleaseChannel", name, args ?? new ReleaseChannelArgs(), MakeResourceOptions(options, ""))
        {
        }

        private ReleaseChannel(string name, Input<string> id, ReleaseChannelState? state = null, CustomResourceOptions? options = null)
            : base("prodvana:index/releaseChannel:ReleaseChannel", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/prodvana",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing ReleaseChannel resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static ReleaseChannel Get(string name, Input<string> id, ReleaseChannelState? state = null, CustomResourceOptions? options = null)
        {
            return new ReleaseChannel(name, id, state, options);
        }
    }

    public sealed class ReleaseChannelArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Name of the Application this Release Channel belongs to
        /// </summary>
        [Input("application", required: true)]
        public Input<string> Application { get; set; } = null!;

        [Input("constants")]
        private InputList<Inputs.ReleaseChannelConstantArgs>? _constants;

        /// <summary>
        /// Constant values for this release channel
        /// </summary>
        public InputList<Inputs.ReleaseChannelConstantArgs> Constants
        {
            get => _constants ?? (_constants = new InputList<Inputs.ReleaseChannelConstantArgs>());
            set => _constants = value;
        }

        [Input("convergenceProtections")]
        private InputList<Inputs.ReleaseChannelConvergenceProtectionArgs>? _convergenceProtections;

        /// <summary>
        /// Feature Coming Soon
        /// </summary>
        public InputList<Inputs.ReleaseChannelConvergenceProtectionArgs> ConvergenceProtections
        {
            get => _convergenceProtections ?? (_convergenceProtections = new InputList<Inputs.ReleaseChannelConvergenceProtectionArgs>());
            set => _convergenceProtections = value;
        }

        [Input("manualApprovalPreconditions")]
        private InputList<Inputs.ReleaseChannelManualApprovalPreconditionArgs>? _manualApprovalPreconditions;

        /// <summary>
        /// Preconditions requiring manual approval before this release channel can be deployed
        /// </summary>
        public InputList<Inputs.ReleaseChannelManualApprovalPreconditionArgs> ManualApprovalPreconditions
        {
            get => _manualApprovalPreconditions ?? (_manualApprovalPreconditions = new InputList<Inputs.ReleaseChannelManualApprovalPreconditionArgs>());
            set => _manualApprovalPreconditions = value;
        }

        /// <summary>
        /// Release Channel name
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Release Channel policy applied to all services
        /// </summary>
        [Input("policy")]
        public Input<Inputs.ReleaseChannelPolicyArgs>? Policy { get; set; }

        [Input("protections")]
        private InputList<Inputs.ReleaseChannelProtectionArgs>? _protections;

        /// <summary>
        /// Protections applied this release channel
        /// </summary>
        public InputList<Inputs.ReleaseChannelProtectionArgs> Protections
        {
            get => _protections ?? (_protections = new InputList<Inputs.ReleaseChannelProtectionArgs>());
            set => _protections = value;
        }

        [Input("releaseChannelStablePreconditions")]
        private InputList<Inputs.ReleaseChannelReleaseChannelStablePreconditionArgs>? _releaseChannelStablePreconditions;

        /// <summary>
        /// Preconditions requiring other release channels to be stable before this release channel can be deployed
        /// </summary>
        public InputList<Inputs.ReleaseChannelReleaseChannelStablePreconditionArgs> ReleaseChannelStablePreconditions
        {
            get => _releaseChannelStablePreconditions ?? (_releaseChannelStablePreconditions = new InputList<Inputs.ReleaseChannelReleaseChannelStablePreconditionArgs>());
            set => _releaseChannelStablePreconditions = value;
        }

        [Input("runtimes", required: true)]
        private InputList<Inputs.ReleaseChannelRuntimeArgs>? _runtimes;

        /// <summary>
        /// Release Channel policy applied to all services
        /// </summary>
        public InputList<Inputs.ReleaseChannelRuntimeArgs> Runtimes
        {
            get => _runtimes ?? (_runtimes = new InputList<Inputs.ReleaseChannelRuntimeArgs>());
            set => _runtimes = value;
        }

        [Input("serviceInstanceProtections")]
        private InputList<Inputs.ReleaseChannelServiceInstanceProtectionArgs>? _serviceInstanceProtections;

        /// <summary>
        /// Protections applied to service instances in this release channel
        /// </summary>
        public InputList<Inputs.ReleaseChannelServiceInstanceProtectionArgs> ServiceInstanceProtections
        {
            get => _serviceInstanceProtections ?? (_serviceInstanceProtections = new InputList<Inputs.ReleaseChannelServiceInstanceProtectionArgs>());
            set => _serviceInstanceProtections = value;
        }

        public ReleaseChannelArgs()
        {
        }
        public static new ReleaseChannelArgs Empty => new ReleaseChannelArgs();
    }

    public sealed class ReleaseChannelState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Name of the Application this Release Channel belongs to
        /// </summary>
        [Input("application")]
        public Input<string>? Application { get; set; }

        [Input("constants")]
        private InputList<Inputs.ReleaseChannelConstantGetArgs>? _constants;

        /// <summary>
        /// Constant values for this release channel
        /// </summary>
        public InputList<Inputs.ReleaseChannelConstantGetArgs> Constants
        {
            get => _constants ?? (_constants = new InputList<Inputs.ReleaseChannelConstantGetArgs>());
            set => _constants = value;
        }

        [Input("convergenceProtections")]
        private InputList<Inputs.ReleaseChannelConvergenceProtectionGetArgs>? _convergenceProtections;

        /// <summary>
        /// Feature Coming Soon
        /// </summary>
        public InputList<Inputs.ReleaseChannelConvergenceProtectionGetArgs> ConvergenceProtections
        {
            get => _convergenceProtections ?? (_convergenceProtections = new InputList<Inputs.ReleaseChannelConvergenceProtectionGetArgs>());
            set => _convergenceProtections = value;
        }

        [Input("manualApprovalPreconditions")]
        private InputList<Inputs.ReleaseChannelManualApprovalPreconditionGetArgs>? _manualApprovalPreconditions;

        /// <summary>
        /// Preconditions requiring manual approval before this release channel can be deployed
        /// </summary>
        public InputList<Inputs.ReleaseChannelManualApprovalPreconditionGetArgs> ManualApprovalPreconditions
        {
            get => _manualApprovalPreconditions ?? (_manualApprovalPreconditions = new InputList<Inputs.ReleaseChannelManualApprovalPreconditionGetArgs>());
            set => _manualApprovalPreconditions = value;
        }

        /// <summary>
        /// Release Channel name
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Release Channel policy applied to all services
        /// </summary>
        [Input("policy")]
        public Input<Inputs.ReleaseChannelPolicyGetArgs>? Policy { get; set; }

        [Input("protections")]
        private InputList<Inputs.ReleaseChannelProtectionGetArgs>? _protections;

        /// <summary>
        /// Protections applied this release channel
        /// </summary>
        public InputList<Inputs.ReleaseChannelProtectionGetArgs> Protections
        {
            get => _protections ?? (_protections = new InputList<Inputs.ReleaseChannelProtectionGetArgs>());
            set => _protections = value;
        }

        [Input("releaseChannelStablePreconditions")]
        private InputList<Inputs.ReleaseChannelReleaseChannelStablePreconditionGetArgs>? _releaseChannelStablePreconditions;

        /// <summary>
        /// Preconditions requiring other release channels to be stable before this release channel can be deployed
        /// </summary>
        public InputList<Inputs.ReleaseChannelReleaseChannelStablePreconditionGetArgs> ReleaseChannelStablePreconditions
        {
            get => _releaseChannelStablePreconditions ?? (_releaseChannelStablePreconditions = new InputList<Inputs.ReleaseChannelReleaseChannelStablePreconditionGetArgs>());
            set => _releaseChannelStablePreconditions = value;
        }

        [Input("runtimes")]
        private InputList<Inputs.ReleaseChannelRuntimeGetArgs>? _runtimes;

        /// <summary>
        /// Release Channel policy applied to all services
        /// </summary>
        public InputList<Inputs.ReleaseChannelRuntimeGetArgs> Runtimes
        {
            get => _runtimes ?? (_runtimes = new InputList<Inputs.ReleaseChannelRuntimeGetArgs>());
            set => _runtimes = value;
        }

        [Input("serviceInstanceProtections")]
        private InputList<Inputs.ReleaseChannelServiceInstanceProtectionGetArgs>? _serviceInstanceProtections;

        /// <summary>
        /// Protections applied to service instances in this release channel
        /// </summary>
        public InputList<Inputs.ReleaseChannelServiceInstanceProtectionGetArgs> ServiceInstanceProtections
        {
            get => _serviceInstanceProtections ?? (_serviceInstanceProtections = new InputList<Inputs.ReleaseChannelServiceInstanceProtectionGetArgs>());
            set => _serviceInstanceProtections = value;
        }

        /// <summary>
        /// Current application version
        /// </summary>
        [Input("version")]
        public Input<string>? Version { get; set; }

        public ReleaseChannelState()
        {
        }
        public static new ReleaseChannelState Empty => new ReleaseChannelState();
    }
}
