// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("prodvana");

/**
 * An API token generated with permissions to this organization.
 */
export declare const apiToken: string | undefined;
Object.defineProperty(exports, "apiToken", {
    get() {
        return __config.get("apiToken") ?? utilities.getEnv("PVN_API_TOKEN");
    },
    enumerable: true,
});

/**
 * Prodvana organization to authenticate with (you can find this in your Org's url: <org>.prodvana.io)
 */
export declare const orgSlug: string | undefined;
Object.defineProperty(exports, "orgSlug", {
    get() {
        return __config.get("orgSlug") ?? utilities.getEnv("PVN_ORG_SLUG");
    },
    enumerable: true,
});

