// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Prodvana.Outputs
{

    [OutputType]
    public sealed class GetReleaseChannelProtectionResult
    {
        /// <summary>
        /// deployment lifecycle options
        /// </summary>
        public readonly Outputs.GetReleaseChannelProtectionDeploymentResult? Deployment;
        /// <summary>
        /// name of the protection
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// post-approval lifecycle options
        /// </summary>
        public readonly Outputs.GetReleaseChannelProtectionPostApprovalResult? PostApproval;
        /// <summary>
        /// post-deployment lifecycle options
        /// </summary>
        public readonly Outputs.GetReleaseChannelProtectionPostDeploymentResult? PostDeployment;
        /// <summary>
        /// pre-approval lifecycle options
        /// </summary>
        public readonly Outputs.GetReleaseChannelProtectionPreApprovalResult? PreApproval;
        /// <summary>
        /// reference to a protection stored in Prodvana
        /// </summary>
        public readonly Outputs.GetReleaseChannelProtectionRefResult Ref;

        [OutputConstructor]
        private GetReleaseChannelProtectionResult(
            Outputs.GetReleaseChannelProtectionDeploymentResult? deployment,

            string name,

            Outputs.GetReleaseChannelProtectionPostApprovalResult? postApproval,

            Outputs.GetReleaseChannelProtectionPostDeploymentResult? postDeployment,

            Outputs.GetReleaseChannelProtectionPreApprovalResult? preApproval,

            Outputs.GetReleaseChannelProtectionRefResult @ref)
        {
            Deployment = deployment;
            Name = name;
            PostApproval = postApproval;
            PostDeployment = postDeployment;
            PreApproval = preApproval;
            Ref = @ref;
        }
    }
}
