// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Prodvana.Outputs
{

    [OutputType]
    public sealed class GetReleaseChannelConvergenceProtectionRefResult
    {
        /// <summary>
        /// name of the constant
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// parameters to pass to the protection
        /// </summary>
        public readonly ImmutableArray<Outputs.GetReleaseChannelConvergenceProtectionRefParameterResult> Parameters;

        [OutputConstructor]
        private GetReleaseChannelConvergenceProtectionRefResult(
            string name,

            ImmutableArray<Outputs.GetReleaseChannelConvergenceProtectionRefParameterResult> parameters)
        {
            Name = name;
            Parameters = parameters;
        }
    }
}
