// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Prodvana.Outputs
{

    [OutputType]
    public sealed class GetReleaseChannelRuntimeResult
    {
        /// <summary>
        /// ECS prefix
        /// </summary>
        public readonly string EcsPrefix;
        /// <summary>
        /// Kubernetes namespace
        /// </summary>
        public readonly string K8sNamespace;
        /// <summary>
        /// optional identifier for this runtime connection within this release channel
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// name of the a runtime
        /// </summary>
        public readonly string? Runtime;
        /// <summary>
        /// type of the runtime connection, one of (EXTENSION, LONG*LIVED*COMPUTE, UNKNOWN_CONNECTION)
        /// </summary>
        public readonly string Type;

        [OutputConstructor]
        private GetReleaseChannelRuntimeResult(
            string ecsPrefix,

            string k8sNamespace,

            string name,

            string? runtime,

            string type)
        {
            EcsPrefix = ecsPrefix;
            K8sNamespace = k8sNamespace;
            Name = name;
            Runtime = runtime;
            Type = type;
        }
    }
}
