// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Prodvana.Outputs
{

    [OutputType]
    public sealed class GetReleaseChannelManualApprovalPreconditionResult
    {
        /// <summary>
        /// description of the manual approval
        /// </summary>
        public readonly string? Description;
        /// <summary>
        /// whether to require manual approval for every action, or just the first
        /// </summary>
        public readonly bool? EveryAction;
        /// <summary>
        /// name of the manual approval
        /// </summary>
        public readonly string Name;

        [OutputConstructor]
        private GetReleaseChannelManualApprovalPreconditionResult(
            string? description,

            bool? everyAction,

            string name)
        {
            Description = description;
            EveryAction = everyAction;
            Name = name;
        }
    }
}
