// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Prodvana.Outputs
{

    [OutputType]
    public sealed class GetReleaseChannelConstantResult
    {
        /// <summary>
        /// name of the constant
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// string value of the constant
        /// </summary>
        public readonly string StringValue;

        [OutputConstructor]
        private GetReleaseChannelConstantResult(
            string name,

            string stringValue)
        {
            Name = name;
            StringValue = stringValue;
        }
    }
}
