// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Prodvana.Outputs
{

    [OutputType]
    public sealed class GetReleaseChannelConvergenceProtectionResult
    {
        /// <summary>
        /// deployment lifecycle options
        /// </summary>
        public readonly Outputs.GetReleaseChannelConvergenceProtectionDeploymentResult? Deployment;
        /// <summary>
        /// name of the protection
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// post-approval lifecycle options
        /// </summary>
        public readonly Outputs.GetReleaseChannelConvergenceProtectionPostApprovalResult? PostApproval;
        /// <summary>
        /// post-deployment lifecycle options
        /// </summary>
        public readonly Outputs.GetReleaseChannelConvergenceProtectionPostDeploymentResult? PostDeployment;
        /// <summary>
        /// pre-approval lifecycle options
        /// </summary>
        public readonly Outputs.GetReleaseChannelConvergenceProtectionPreApprovalResult? PreApproval;
        /// <summary>
        /// reference to a protection stored in Prodvana
        /// </summary>
        public readonly Outputs.GetReleaseChannelConvergenceProtectionRefResult Ref;

        [OutputConstructor]
        private GetReleaseChannelConvergenceProtectionResult(
            Outputs.GetReleaseChannelConvergenceProtectionDeploymentResult? deployment,

            string name,

            Outputs.GetReleaseChannelConvergenceProtectionPostApprovalResult? postApproval,

            Outputs.GetReleaseChannelConvergenceProtectionPostDeploymentResult? postDeployment,

            Outputs.GetReleaseChannelConvergenceProtectionPreApprovalResult? preApproval,

            Outputs.GetReleaseChannelConvergenceProtectionRefResult @ref)
        {
            Deployment = deployment;
            Name = name;
            PostApproval = postApproval;
            PostDeployment = postDeployment;
            PreApproval = preApproval;
            Ref = @ref;
        }
    }
}
