// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Prodvana.Outputs
{

    [OutputType]
    public sealed class ReleaseChannelProtectionRefParameter
    {
        public readonly string? DockerImageTagValue;
        public readonly int? IntValue;
        /// <summary>
        /// Release Channel name
        /// </summary>
        public readonly string Name;
        public readonly Outputs.ReleaseChannelProtectionRefParameterSecretValue? SecretValue;
        public readonly string? StringValue;

        [OutputConstructor]
        private ReleaseChannelProtectionRefParameter(
            string? dockerImageTagValue,

            int? intValue,

            string name,

            Outputs.ReleaseChannelProtectionRefParameterSecretValue? secretValue,

            string? stringValue)
        {
            DockerImageTagValue = dockerImageTagValue;
            IntValue = intValue;
            Name = name;
            SecretValue = secretValue;
            StringValue = stringValue;
        }
    }
}
