// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Prodvana.Outputs
{

    [OutputType]
    public sealed class ReleaseChannelPolicy
    {
        /// <summary>
        /// default environment variables for services in this Release Channel
        /// </summary>
        public readonly ImmutableDictionary<string, Outputs.ReleaseChannelPolicyDefaultEnv>? DefaultEnv;

        [OutputConstructor]
        private ReleaseChannelPolicy(ImmutableDictionary<string, Outputs.ReleaseChannelPolicyDefaultEnv>? defaultEnv)
        {
            DefaultEnv = defaultEnv;
        }
    }
}
