// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Prodvana.Outputs
{

    [OutputType]
    public sealed class ReleaseChannelRuntime
    {
        /// <summary>
        /// Prefix used when naming ECS resources. Can only be set on an ECS Runtime.
        /// </summary>
        public readonly string? EcsPrefix;
        /// <summary>
        /// Optionally set a custom namespace. If not set, Prodvana will create and manage the namespace. If set, the namespace *must* already exist and Prodvana will not try to create or delete it. Can only be set on a Kubernetes Runtime.
        /// </summary>
        public readonly string? K8sNamespace;
        /// <summary>
        /// optional identifier for this runtime connection within this release channel
        /// </summary>
        public readonly string? Name;
        /// <summary>
        /// name of the a runtime
        /// </summary>
        public readonly string? Runtime;
        /// <summary>
        /// type of the runtime connection, one of (EXTENSION, LONG*LIVED*COMPUTE, UNKNOWN_CONNECTION)
        /// </summary>
        public readonly string? Type;

        [OutputConstructor]
        private ReleaseChannelRuntime(
            string? ecsPrefix,

            string? k8sNamespace,

            string? name,

            string? runtime,

            string? type)
        {
            EcsPrefix = ecsPrefix;
            K8sNamespace = k8sNamespace;
            Name = name;
            Runtime = runtime;
            Type = type;
        }
    }
}
