// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Prodvana.Outputs
{

    [OutputType]
    public sealed class ReleaseChannelServiceInstanceProtectionPostDeployment
    {
        public readonly string? CheckDuration;
        public readonly string? DelayCheckDuration;
        public readonly bool? Enabled;

        [OutputConstructor]
        private ReleaseChannelServiceInstanceProtectionPostDeployment(
            string? checkDuration,

            string? delayCheckDuration,

            bool? enabled)
        {
            CheckDuration = checkDuration;
            DelayCheckDuration = delayCheckDuration;
            Enabled = enabled;
        }
    }
}
