// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Prodvana.Outputs
{

    [OutputType]
    public sealed class ReleaseChannelServiceInstanceProtection
    {
        /// <summary>
        /// deployment lifecycle options
        /// </summary>
        public readonly Outputs.ReleaseChannelServiceInstanceProtectionDeployment? Deployment;
        /// <summary>
        /// name of the protection
        /// </summary>
        public readonly string? Name;
        /// <summary>
        /// post-approval lifecycle options
        /// </summary>
        public readonly Outputs.ReleaseChannelServiceInstanceProtectionPostApproval? PostApproval;
        /// <summary>
        /// post-deployment lifecycle options
        /// </summary>
        public readonly Outputs.ReleaseChannelServiceInstanceProtectionPostDeployment? PostDeployment;
        /// <summary>
        /// pre-approval lifecycle options
        /// </summary>
        public readonly Outputs.ReleaseChannelServiceInstanceProtectionPreApproval? PreApproval;
        /// <summary>
        /// reference to a protection stored in Prodvana
        /// </summary>
        public readonly Outputs.ReleaseChannelServiceInstanceProtectionRef Ref;

        [OutputConstructor]
        private ReleaseChannelServiceInstanceProtection(
            Outputs.ReleaseChannelServiceInstanceProtectionDeployment? deployment,

            string? name,

            Outputs.ReleaseChannelServiceInstanceProtectionPostApproval? postApproval,

            Outputs.ReleaseChannelServiceInstanceProtectionPostDeployment? postDeployment,

            Outputs.ReleaseChannelServiceInstanceProtectionPreApproval? preApproval,

            Outputs.ReleaseChannelServiceInstanceProtectionRef @ref)
        {
            Deployment = deployment;
            Name = name;
            PostApproval = postApproval;
            PostDeployment = postDeployment;
            PreApproval = preApproval;
            Ref = @ref;
        }
    }
}
