// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Prodvana.Outputs
{

    [OutputType]
    public sealed class ReleaseChannelPolicyDefaultEnv
    {
        public readonly Outputs.ReleaseChannelPolicyDefaultEnvSecret? Secret;
        public readonly string? Value;

        [OutputConstructor]
        private ReleaseChannelPolicyDefaultEnv(
            Outputs.ReleaseChannelPolicyDefaultEnvSecret? secret,

            string? value)
        {
            Secret = secret;
            Value = value;
        }
    }
}
