// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Prodvana.Outputs
{

    [OutputType]
    public sealed class ReleaseChannelPolicyDefaultEnv
    {
        /// <summary>
        /// Reference to a secret value stored in Kubernetes.
        /// </summary>
        public readonly Outputs.ReleaseChannelPolicyDefaultEnvKubernetesSecret? KubernetesSecret;
        /// <summary>
        /// Reference to a secret value stored in Prodvana.
        /// </summary>
        public readonly Outputs.ReleaseChannelPolicyDefaultEnvSecret? Secret;
        /// <summary>
        /// Non-sensitive environment variable value
        /// </summary>
        public readonly string? Value;

        [OutputConstructor]
        private ReleaseChannelPolicyDefaultEnv(
            Outputs.ReleaseChannelPolicyDefaultEnvKubernetesSecret? kubernetesSecret,

            Outputs.ReleaseChannelPolicyDefaultEnvSecret? secret,

            string? value)
        {
            KubernetesSecret = kubernetesSecret;
            Secret = secret;
            Value = value;
        }
    }
}
