// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Prodvana.Outputs
{

    [OutputType]
    public sealed class ReleaseChannelManualApprovalPrecondition
    {
        /// <summary>
        /// description of the manual approval
        /// </summary>
        public readonly string? Description;
        /// <summary>
        /// whether this approval is required for every convergence action, or just the first
        /// </summary>
        public readonly bool? EveryAction;
        /// <summary>
        /// name of the manual approval
        /// </summary>
        public readonly string Name;

        [OutputConstructor]
        private ReleaseChannelManualApprovalPrecondition(
            string? description,

            bool? everyAction,

            string name)
        {
            Description = description;
            EveryAction = everyAction;
            Name = name;
        }
    }
}
