// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface GetK8sRuntimeLabel {
    /**
     * Label name
     */
    label: string;
    /**
     * Label value
     */
    value: string;
}

export interface GetK8sRuntimeLabelArgs {
    /**
     * Label name
     */
    label: pulumi.Input<string>;
    /**
     * Label value
     */
    value: pulumi.Input<string>;
}

export interface GetReleaseChannelConstant {
    /**
     * name of the constant
     */
    name: string;
    /**
     * string value of the constant
     */
    stringValue: string;
}

export interface GetReleaseChannelConstantArgs {
    /**
     * name of the constant
     */
    name: pulumi.Input<string>;
    /**
     * string value of the constant
     */
    stringValue: pulumi.Input<string>;
}

export interface GetReleaseChannelConvergenceProtection {
    /**
     * deployment lifecycle options
     */
    deployment?: inputs.GetReleaseChannelConvergenceProtectionDeployment;
    /**
     * name of the protection
     */
    name?: string;
    /**
     * post-approval lifecycle options
     */
    postApproval?: inputs.GetReleaseChannelConvergenceProtectionPostApproval;
    /**
     * post-deployment lifecycle options
     */
    postDeployment?: inputs.GetReleaseChannelConvergenceProtectionPostDeployment;
    /**
     * pre-approval lifecycle options
     */
    preApproval?: inputs.GetReleaseChannelConvergenceProtectionPreApproval;
    /**
     * reference to a protection stored in Prodvana
     */
    ref: inputs.GetReleaseChannelConvergenceProtectionRef;
}

export interface GetReleaseChannelConvergenceProtectionArgs {
    /**
     * deployment lifecycle options
     */
    deployment?: pulumi.Input<inputs.GetReleaseChannelConvergenceProtectionDeploymentArgs>;
    /**
     * name of the protection
     */
    name?: pulumi.Input<string>;
    /**
     * post-approval lifecycle options
     */
    postApproval?: pulumi.Input<inputs.GetReleaseChannelConvergenceProtectionPostApprovalArgs>;
    /**
     * post-deployment lifecycle options
     */
    postDeployment?: pulumi.Input<inputs.GetReleaseChannelConvergenceProtectionPostDeploymentArgs>;
    /**
     * pre-approval lifecycle options
     */
    preApproval?: pulumi.Input<inputs.GetReleaseChannelConvergenceProtectionPreApprovalArgs>;
    /**
     * reference to a protection stored in Prodvana
     */
    ref: pulumi.Input<inputs.GetReleaseChannelConvergenceProtectionRefArgs>;
}

export interface GetReleaseChannelConvergenceProtectionDeployment {
    /**
     * whether to enable deployment lifecycle options
     */
    enabled?: boolean;
}

export interface GetReleaseChannelConvergenceProtectionDeploymentArgs {
    /**
     * whether to enable deployment lifecycle options
     */
    enabled?: pulumi.Input<boolean>;
}

export interface GetReleaseChannelConvergenceProtectionPostApproval {
    /**
     * whether to enable deployment lifecycle options
     */
    enabled?: boolean;
}

export interface GetReleaseChannelConvergenceProtectionPostApprovalArgs {
    /**
     * whether to enable deployment lifecycle options
     */
    enabled?: pulumi.Input<boolean>;
}

export interface GetReleaseChannelConvergenceProtectionPostDeployment {
    /**
     * how long to keep checking. A valid Go duration string, e.g. `10m` or `1h`. Defaults to `10m`
     */
    checkDuration?: string;
    /**
     * delay between the deployment completing and when this protection starts checking. A valid Go duration string, e.g. `10m` or `1h`. Defaults to `10m`
     */
    delayCheckDuration?: string;
    /**
     * whether to enable deployment lifecycle options
     */
    enabled?: boolean;
}

export interface GetReleaseChannelConvergenceProtectionPostDeploymentArgs {
    /**
     * how long to keep checking. A valid Go duration string, e.g. `10m` or `1h`. Defaults to `10m`
     */
    checkDuration?: pulumi.Input<string>;
    /**
     * delay between the deployment completing and when this protection starts checking. A valid Go duration string, e.g. `10m` or `1h`. Defaults to `10m`
     */
    delayCheckDuration?: pulumi.Input<string>;
    /**
     * whether to enable deployment lifecycle options
     */
    enabled?: pulumi.Input<boolean>;
}

export interface GetReleaseChannelConvergenceProtectionPreApproval {
    /**
     * whether to enable deployment lifecycle options
     */
    enabled?: boolean;
}

export interface GetReleaseChannelConvergenceProtectionPreApprovalArgs {
    /**
     * whether to enable deployment lifecycle options
     */
    enabled?: pulumi.Input<boolean>;
}

export interface GetReleaseChannelConvergenceProtectionRef {
    /**
     * name of the constant
     */
    name: string;
    /**
     * parameters to pass to the protection
     */
    parameters?: inputs.GetReleaseChannelConvergenceProtectionRefParameter[];
}

export interface GetReleaseChannelConvergenceProtectionRefArgs {
    /**
     * name of the constant
     */
    name: pulumi.Input<string>;
    /**
     * parameters to pass to the protection
     */
    parameters?: pulumi.Input<pulumi.Input<inputs.GetReleaseChannelConvergenceProtectionRefParameterArgs>[]>;
}

export interface GetReleaseChannelConvergenceProtectionRefParameter {
    /**
     * parameter docker image tag value, only one of (string*value, int*value, docker*image*tag*value, secret*value) can be set
     */
    dockerImageTagValue?: string;
    /**
     * parameter int value, only one of (string*value, int*value, docker*image*tag*value, secret*value) can be set
     */
    intValue?: number;
    /**
     * name of the constant
     */
    name: string;
    /**
     * parameter secret value, only one of (string*value, int*value, docker*image*tag*value, secret*value) can be set
     */
    secretValue?: inputs.GetReleaseChannelConvergenceProtectionRefParameterSecretValue;
    /**
     * string value of the constant
     */
    stringValue?: string;
}

export interface GetReleaseChannelConvergenceProtectionRefParameterArgs {
    /**
     * parameter docker image tag value, only one of (string*value, int*value, docker*image*tag*value, secret*value) can be set
     */
    dockerImageTagValue?: pulumi.Input<string>;
    /**
     * parameter int value, only one of (string*value, int*value, docker*image*tag*value, secret*value) can be set
     */
    intValue?: pulumi.Input<number>;
    /**
     * name of the constant
     */
    name: pulumi.Input<string>;
    /**
     * parameter secret value, only one of (string*value, int*value, docker*image*tag*value, secret*value) can be set
     */
    secretValue?: pulumi.Input<inputs.GetReleaseChannelConvergenceProtectionRefParameterSecretValueArgs>;
    /**
     * string value of the constant
     */
    stringValue?: pulumi.Input<string>;
}

export interface GetReleaseChannelConvergenceProtectionRefParameterSecretValue {
    /**
     * Name of the secret.
     */
    key: string;
    /**
     * Version of the secret
     */
    version: string;
}

export interface GetReleaseChannelConvergenceProtectionRefParameterSecretValueArgs {
    /**
     * Name of the secret.
     */
    key: pulumi.Input<string>;
    /**
     * Version of the secret
     */
    version: pulumi.Input<string>;
}

export interface GetReleaseChannelManualApprovalPrecondition {
    /**
     * description of the manual approval
     */
    description?: string;
    /**
     * whether to require manual approval for every action, or just the first
     */
    everyAction?: boolean;
    /**
     * name of the manual approval
     */
    name: string;
}

export interface GetReleaseChannelManualApprovalPreconditionArgs {
    /**
     * description of the manual approval
     */
    description?: pulumi.Input<string>;
    /**
     * whether to require manual approval for every action, or just the first
     */
    everyAction?: pulumi.Input<boolean>;
    /**
     * name of the manual approval
     */
    name: pulumi.Input<string>;
}

export interface GetReleaseChannelPolicy {
    /**
     * default environment variables for services in this Release Channel
     */
    defaultEnv?: {[key: string]: inputs.GetReleaseChannelPolicyDefaultEnv};
}

export interface GetReleaseChannelPolicyArgs {
    /**
     * default environment variables for services in this Release Channel
     */
    defaultEnv?: pulumi.Input<{[key: string]: pulumi.Input<inputs.GetReleaseChannelPolicyDefaultEnvArgs>}>;
}

export interface GetReleaseChannelPolicyDefaultEnv {
    /**
     * Reference to a secret value stored in Kubernetes.
     */
    kubernetesSecret?: inputs.GetReleaseChannelPolicyDefaultEnvKubernetesSecret;
    /**
     * Reference to a secret value stored in Prodvana.
     */
    secret?: inputs.GetReleaseChannelPolicyDefaultEnvSecret;
    /**
     * Non-sensitive environment variable value
     */
    value?: string;
}

export interface GetReleaseChannelPolicyDefaultEnvArgs {
    /**
     * Reference to a secret value stored in Kubernetes.
     */
    kubernetesSecret?: pulumi.Input<inputs.GetReleaseChannelPolicyDefaultEnvKubernetesSecretArgs>;
    /**
     * Reference to a secret value stored in Prodvana.
     */
    secret?: pulumi.Input<inputs.GetReleaseChannelPolicyDefaultEnvSecretArgs>;
    /**
     * Non-sensitive environment variable value
     */
    value?: pulumi.Input<string>;
}

export interface GetReleaseChannelPolicyDefaultEnvKubernetesSecret {
    /**
     * Name of the secret.
     */
    key?: string;
    /**
     * Name of the secret object
     */
    secretName?: string;
}

export interface GetReleaseChannelPolicyDefaultEnvKubernetesSecretArgs {
    /**
     * Name of the secret.
     */
    key?: pulumi.Input<string>;
    /**
     * Name of the secret object
     */
    secretName?: pulumi.Input<string>;
}

export interface GetReleaseChannelPolicyDefaultEnvSecret {
    /**
     * Name of the secret.
     */
    key?: string;
    /**
     * Version of the secret
     */
    version?: string;
}

export interface GetReleaseChannelPolicyDefaultEnvSecretArgs {
    /**
     * Name of the secret.
     */
    key?: pulumi.Input<string>;
    /**
     * Version of the secret
     */
    version?: pulumi.Input<string>;
}

export interface GetReleaseChannelProtection {
    /**
     * deployment lifecycle options
     */
    deployment?: inputs.GetReleaseChannelProtectionDeployment;
    /**
     * name of the protection
     */
    name?: string;
    /**
     * post-approval lifecycle options
     */
    postApproval?: inputs.GetReleaseChannelProtectionPostApproval;
    /**
     * post-deployment lifecycle options
     */
    postDeployment?: inputs.GetReleaseChannelProtectionPostDeployment;
    /**
     * pre-approval lifecycle options
     */
    preApproval?: inputs.GetReleaseChannelProtectionPreApproval;
    /**
     * reference to a protection stored in Prodvana
     */
    ref: inputs.GetReleaseChannelProtectionRef;
}

export interface GetReleaseChannelProtectionArgs {
    /**
     * deployment lifecycle options
     */
    deployment?: pulumi.Input<inputs.GetReleaseChannelProtectionDeploymentArgs>;
    /**
     * name of the protection
     */
    name?: pulumi.Input<string>;
    /**
     * post-approval lifecycle options
     */
    postApproval?: pulumi.Input<inputs.GetReleaseChannelProtectionPostApprovalArgs>;
    /**
     * post-deployment lifecycle options
     */
    postDeployment?: pulumi.Input<inputs.GetReleaseChannelProtectionPostDeploymentArgs>;
    /**
     * pre-approval lifecycle options
     */
    preApproval?: pulumi.Input<inputs.GetReleaseChannelProtectionPreApprovalArgs>;
    /**
     * reference to a protection stored in Prodvana
     */
    ref: pulumi.Input<inputs.GetReleaseChannelProtectionRefArgs>;
}

export interface GetReleaseChannelProtectionDeployment {
    /**
     * whether to enable deployment lifecycle options
     */
    enabled?: boolean;
}

export interface GetReleaseChannelProtectionDeploymentArgs {
    /**
     * whether to enable deployment lifecycle options
     */
    enabled?: pulumi.Input<boolean>;
}

export interface GetReleaseChannelProtectionPostApproval {
    /**
     * whether to enable deployment lifecycle options
     */
    enabled?: boolean;
}

export interface GetReleaseChannelProtectionPostApprovalArgs {
    /**
     * whether to enable deployment lifecycle options
     */
    enabled?: pulumi.Input<boolean>;
}

export interface GetReleaseChannelProtectionPostDeployment {
    /**
     * how long to keep checking. A valid Go duration string, e.g. `10m` or `1h`. Defaults to `10m`
     */
    checkDuration?: string;
    /**
     * delay between the deployment completing and when this protection starts checking. A valid Go duration string, e.g. `10m` or `1h`. Defaults to `10m`
     */
    delayCheckDuration?: string;
    /**
     * whether to enable deployment lifecycle options
     */
    enabled?: boolean;
}

export interface GetReleaseChannelProtectionPostDeploymentArgs {
    /**
     * how long to keep checking. A valid Go duration string, e.g. `10m` or `1h`. Defaults to `10m`
     */
    checkDuration?: pulumi.Input<string>;
    /**
     * delay between the deployment completing and when this protection starts checking. A valid Go duration string, e.g. `10m` or `1h`. Defaults to `10m`
     */
    delayCheckDuration?: pulumi.Input<string>;
    /**
     * whether to enable deployment lifecycle options
     */
    enabled?: pulumi.Input<boolean>;
}

export interface GetReleaseChannelProtectionPreApproval {
    /**
     * whether to enable deployment lifecycle options
     */
    enabled?: boolean;
}

export interface GetReleaseChannelProtectionPreApprovalArgs {
    /**
     * whether to enable deployment lifecycle options
     */
    enabled?: pulumi.Input<boolean>;
}

export interface GetReleaseChannelProtectionRef {
    /**
     * name of the constant
     */
    name: string;
    /**
     * parameters to pass to the protection
     */
    parameters?: inputs.GetReleaseChannelProtectionRefParameter[];
}

export interface GetReleaseChannelProtectionRefArgs {
    /**
     * name of the constant
     */
    name: pulumi.Input<string>;
    /**
     * parameters to pass to the protection
     */
    parameters?: pulumi.Input<pulumi.Input<inputs.GetReleaseChannelProtectionRefParameterArgs>[]>;
}

export interface GetReleaseChannelProtectionRefParameter {
    /**
     * parameter docker image tag value, only one of (string*value, int*value, docker*image*tag*value, secret*value) can be set
     */
    dockerImageTagValue?: string;
    /**
     * parameter int value, only one of (string*value, int*value, docker*image*tag*value, secret*value) can be set
     */
    intValue?: number;
    /**
     * name of the constant
     */
    name: string;
    /**
     * parameter secret value, only one of (string*value, int*value, docker*image*tag*value, secret*value) can be set
     */
    secretValue?: inputs.GetReleaseChannelProtectionRefParameterSecretValue;
    /**
     * string value of the constant
     */
    stringValue?: string;
}

export interface GetReleaseChannelProtectionRefParameterArgs {
    /**
     * parameter docker image tag value, only one of (string*value, int*value, docker*image*tag*value, secret*value) can be set
     */
    dockerImageTagValue?: pulumi.Input<string>;
    /**
     * parameter int value, only one of (string*value, int*value, docker*image*tag*value, secret*value) can be set
     */
    intValue?: pulumi.Input<number>;
    /**
     * name of the constant
     */
    name: pulumi.Input<string>;
    /**
     * parameter secret value, only one of (string*value, int*value, docker*image*tag*value, secret*value) can be set
     */
    secretValue?: pulumi.Input<inputs.GetReleaseChannelProtectionRefParameterSecretValueArgs>;
    /**
     * string value of the constant
     */
    stringValue?: pulumi.Input<string>;
}

export interface GetReleaseChannelProtectionRefParameterSecretValue {
    /**
     * Name of the secret.
     */
    key: string;
    /**
     * Version of the secret
     */
    version: string;
}

export interface GetReleaseChannelProtectionRefParameterSecretValueArgs {
    /**
     * Name of the secret.
     */
    key: pulumi.Input<string>;
    /**
     * Version of the secret
     */
    version: pulumi.Input<string>;
}

export interface GetReleaseChannelReleaseChannelStablePrecondition {
    /**
     * name of a release channel that must be in a stable deployment state
     */
    releaseChannel: string;
}

export interface GetReleaseChannelReleaseChannelStablePreconditionArgs {
    /**
     * name of a release channel that must be in a stable deployment state
     */
    releaseChannel: pulumi.Input<string>;
}

export interface GetReleaseChannelServiceInstanceProtection {
    /**
     * deployment lifecycle options
     */
    deployment?: inputs.GetReleaseChannelServiceInstanceProtectionDeployment;
    /**
     * name of the protection
     */
    name?: string;
    /**
     * post-approval lifecycle options
     */
    postApproval?: inputs.GetReleaseChannelServiceInstanceProtectionPostApproval;
    /**
     * post-deployment lifecycle options
     */
    postDeployment?: inputs.GetReleaseChannelServiceInstanceProtectionPostDeployment;
    /**
     * pre-approval lifecycle options
     */
    preApproval?: inputs.GetReleaseChannelServiceInstanceProtectionPreApproval;
    /**
     * reference to a protection stored in Prodvana
     */
    ref: inputs.GetReleaseChannelServiceInstanceProtectionRef;
}

export interface GetReleaseChannelServiceInstanceProtectionArgs {
    /**
     * deployment lifecycle options
     */
    deployment?: pulumi.Input<inputs.GetReleaseChannelServiceInstanceProtectionDeploymentArgs>;
    /**
     * name of the protection
     */
    name?: pulumi.Input<string>;
    /**
     * post-approval lifecycle options
     */
    postApproval?: pulumi.Input<inputs.GetReleaseChannelServiceInstanceProtectionPostApprovalArgs>;
    /**
     * post-deployment lifecycle options
     */
    postDeployment?: pulumi.Input<inputs.GetReleaseChannelServiceInstanceProtectionPostDeploymentArgs>;
    /**
     * pre-approval lifecycle options
     */
    preApproval?: pulumi.Input<inputs.GetReleaseChannelServiceInstanceProtectionPreApprovalArgs>;
    /**
     * reference to a protection stored in Prodvana
     */
    ref: pulumi.Input<inputs.GetReleaseChannelServiceInstanceProtectionRefArgs>;
}

export interface GetReleaseChannelServiceInstanceProtectionDeployment {
    /**
     * whether to enable deployment lifecycle options
     */
    enabled?: boolean;
}

export interface GetReleaseChannelServiceInstanceProtectionDeploymentArgs {
    /**
     * whether to enable deployment lifecycle options
     */
    enabled?: pulumi.Input<boolean>;
}

export interface GetReleaseChannelServiceInstanceProtectionPostApproval {
    /**
     * whether to enable deployment lifecycle options
     */
    enabled?: boolean;
}

export interface GetReleaseChannelServiceInstanceProtectionPostApprovalArgs {
    /**
     * whether to enable deployment lifecycle options
     */
    enabled?: pulumi.Input<boolean>;
}

export interface GetReleaseChannelServiceInstanceProtectionPostDeployment {
    /**
     * how long to keep checking. A valid Go duration string, e.g. `10m` or `1h`. Defaults to `10m`
     */
    checkDuration?: string;
    /**
     * delay between the deployment completing and when this protection starts checking. A valid Go duration string, e.g. `10m` or `1h`. Defaults to `10m`
     */
    delayCheckDuration?: string;
    /**
     * whether to enable deployment lifecycle options
     */
    enabled?: boolean;
}

export interface GetReleaseChannelServiceInstanceProtectionPostDeploymentArgs {
    /**
     * how long to keep checking. A valid Go duration string, e.g. `10m` or `1h`. Defaults to `10m`
     */
    checkDuration?: pulumi.Input<string>;
    /**
     * delay between the deployment completing and when this protection starts checking. A valid Go duration string, e.g. `10m` or `1h`. Defaults to `10m`
     */
    delayCheckDuration?: pulumi.Input<string>;
    /**
     * whether to enable deployment lifecycle options
     */
    enabled?: pulumi.Input<boolean>;
}

export interface GetReleaseChannelServiceInstanceProtectionPreApproval {
    /**
     * whether to enable deployment lifecycle options
     */
    enabled?: boolean;
}

export interface GetReleaseChannelServiceInstanceProtectionPreApprovalArgs {
    /**
     * whether to enable deployment lifecycle options
     */
    enabled?: pulumi.Input<boolean>;
}

export interface GetReleaseChannelServiceInstanceProtectionRef {
    /**
     * name of the constant
     */
    name: string;
    /**
     * parameters to pass to the protection
     */
    parameters?: inputs.GetReleaseChannelServiceInstanceProtectionRefParameter[];
}

export interface GetReleaseChannelServiceInstanceProtectionRefArgs {
    /**
     * name of the constant
     */
    name: pulumi.Input<string>;
    /**
     * parameters to pass to the protection
     */
    parameters?: pulumi.Input<pulumi.Input<inputs.GetReleaseChannelServiceInstanceProtectionRefParameterArgs>[]>;
}

export interface GetReleaseChannelServiceInstanceProtectionRefParameter {
    /**
     * parameter docker image tag value, only one of (string*value, int*value, docker*image*tag*value, secret*value) can be set
     */
    dockerImageTagValue?: string;
    /**
     * parameter int value, only one of (string*value, int*value, docker*image*tag*value, secret*value) can be set
     */
    intValue?: number;
    /**
     * name of the constant
     */
    name: string;
    /**
     * parameter secret value, only one of (string*value, int*value, docker*image*tag*value, secret*value) can be set
     */
    secretValue?: inputs.GetReleaseChannelServiceInstanceProtectionRefParameterSecretValue;
    /**
     * string value of the constant
     */
    stringValue?: string;
}

export interface GetReleaseChannelServiceInstanceProtectionRefParameterArgs {
    /**
     * parameter docker image tag value, only one of (string*value, int*value, docker*image*tag*value, secret*value) can be set
     */
    dockerImageTagValue?: pulumi.Input<string>;
    /**
     * parameter int value, only one of (string*value, int*value, docker*image*tag*value, secret*value) can be set
     */
    intValue?: pulumi.Input<number>;
    /**
     * name of the constant
     */
    name: pulumi.Input<string>;
    /**
     * parameter secret value, only one of (string*value, int*value, docker*image*tag*value, secret*value) can be set
     */
    secretValue?: pulumi.Input<inputs.GetReleaseChannelServiceInstanceProtectionRefParameterSecretValueArgs>;
    /**
     * string value of the constant
     */
    stringValue?: pulumi.Input<string>;
}

export interface GetReleaseChannelServiceInstanceProtectionRefParameterSecretValue {
    /**
     * Name of the secret.
     */
    key: string;
    /**
     * Version of the secret
     */
    version: string;
}

export interface GetReleaseChannelServiceInstanceProtectionRefParameterSecretValueArgs {
    /**
     * Name of the secret.
     */
    key: pulumi.Input<string>;
    /**
     * Version of the secret
     */
    version: pulumi.Input<string>;
}

export interface GetReleaseChannelSharedManualApprovalPrecondition {
    /**
     * name of the manual approval
     */
    name?: string;
}

export interface GetReleaseChannelSharedManualApprovalPreconditionArgs {
    /**
     * name of the manual approval
     */
    name?: pulumi.Input<string>;
}

export interface K8sRuntimeLabel {
    /**
     * Label name
     */
    label: pulumi.Input<string>;
    /**
     * Label value
     */
    value: pulumi.Input<string>;
}

export interface ManagedK8sRuntimeExec {
    /**
     * API version of the exec credential plugin
     */
    apiVersion: pulumi.Input<string>;
    /**
     * Arguments to pass when executing the command
     */
    args?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Command to execute
     */
    command: pulumi.Input<string>;
    /**
     * Environment variables to set when executing the command
     */
    env?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
}

export interface ManagedK8sRuntimeLabel {
    /**
     * Label name
     */
    label: pulumi.Input<string>;
    /**
     * Label value
     */
    value: pulumi.Input<string>;
}

export interface ReleaseChannelConstant {
    /**
     * name of the constant
     */
    name: pulumi.Input<string>;
    /**
     * string value of the constant
     */
    stringValue: pulumi.Input<string>;
}

export interface ReleaseChannelConvergenceProtection {
    /**
     * deployment lifecycle options
     */
    deployment?: pulumi.Input<inputs.ReleaseChannelConvergenceProtectionDeployment>;
    /**
     * name of the protection
     */
    name?: pulumi.Input<string>;
    /**
     * post-approval lifecycle options
     */
    postApproval?: pulumi.Input<inputs.ReleaseChannelConvergenceProtectionPostApproval>;
    /**
     * post-deployment lifecycle options
     */
    postDeployment?: pulumi.Input<inputs.ReleaseChannelConvergenceProtectionPostDeployment>;
    /**
     * pre-approval lifecycle options
     */
    preApproval?: pulumi.Input<inputs.ReleaseChannelConvergenceProtectionPreApproval>;
    /**
     * reference to a protection stored in Prodvana
     */
    ref: pulumi.Input<inputs.ReleaseChannelConvergenceProtectionRef>;
}

export interface ReleaseChannelConvergenceProtectionDeployment {
    /**
     * whether to enable deployment lifecycle options
     */
    enabled?: pulumi.Input<boolean>;
}

export interface ReleaseChannelConvergenceProtectionPostApproval {
    /**
     * whether to enable deployment lifecycle options
     */
    enabled?: pulumi.Input<boolean>;
}

export interface ReleaseChannelConvergenceProtectionPostDeployment {
    /**
     * how long to keep checking. A valid Go duration string, e.g. `10m` or `1h`. Defaults to `10m`
     */
    checkDuration?: pulumi.Input<string>;
    /**
     * delay between the deployment completing and when this protection starts checking. A valid Go duration string, e.g. `10m` or `1h`. Defaults to `10m`
     */
    delayCheckDuration?: pulumi.Input<string>;
    /**
     * whether to enable deployment lifecycle options
     */
    enabled?: pulumi.Input<boolean>;
}

export interface ReleaseChannelConvergenceProtectionPreApproval {
    /**
     * whether to enable deployment lifecycle options
     */
    enabled?: pulumi.Input<boolean>;
}

export interface ReleaseChannelConvergenceProtectionRef {
    /**
     * name of the constant
     */
    name: pulumi.Input<string>;
    /**
     * parameters to pass to the protection
     */
    parameters?: pulumi.Input<pulumi.Input<inputs.ReleaseChannelConvergenceProtectionRefParameter>[]>;
}

export interface ReleaseChannelConvergenceProtectionRefParameter {
    /**
     * parameter docker image tag value, only one of (string*value, int*value, docker*image*tag*value, secret*value) can be set
     */
    dockerImageTagValue?: pulumi.Input<string>;
    /**
     * parameter int value, only one of (string*value, int*value, docker*image*tag*value, secret*value) can be set
     */
    intValue?: pulumi.Input<number>;
    /**
     * name of the constant
     */
    name: pulumi.Input<string>;
    /**
     * parameter secret value, only one of (string*value, int*value, docker*image*tag*value, secret*value) can be set
     */
    secretValue?: pulumi.Input<inputs.ReleaseChannelConvergenceProtectionRefParameterSecretValue>;
    /**
     * string value of the constant
     */
    stringValue?: pulumi.Input<string>;
}

export interface ReleaseChannelConvergenceProtectionRefParameterSecretValue {
    /**
     * Name of the secret.
     */
    key: pulumi.Input<string>;
    /**
     * Version of the secret
     */
    version: pulumi.Input<string>;
}

export interface ReleaseChannelManualApprovalPrecondition {
    /**
     * description of the manual approval
     */
    description?: pulumi.Input<string>;
    everyAction?: pulumi.Input<boolean>;
    /**
     * name of the manual approval
     */
    name?: pulumi.Input<string>;
}

export interface ReleaseChannelPolicy {
    /**
     * default environment variables for services in this Release Channel
     */
    defaultEnv?: pulumi.Input<{[key: string]: pulumi.Input<inputs.ReleaseChannelPolicyDefaultEnv>}>;
}

export interface ReleaseChannelPolicyDefaultEnv {
    /**
     * Reference to a secret value stored in Kubernetes.
     */
    kubernetesSecret?: pulumi.Input<inputs.ReleaseChannelPolicyDefaultEnvKubernetesSecret>;
    /**
     * Reference to a secret value stored in Prodvana.
     */
    secret?: pulumi.Input<inputs.ReleaseChannelPolicyDefaultEnvSecret>;
    /**
     * Non-sensitive environment variable value
     */
    value?: pulumi.Input<string>;
}

export interface ReleaseChannelPolicyDefaultEnvKubernetesSecret {
    /**
     * Name of the secret.
     */
    key?: pulumi.Input<string>;
    /**
     * Name of the secret object
     */
    secretName?: pulumi.Input<string>;
}

export interface ReleaseChannelPolicyDefaultEnvSecret {
    /**
     * Name of the secret.
     */
    key?: pulumi.Input<string>;
    /**
     * Version of the secret
     */
    version?: pulumi.Input<string>;
}

export interface ReleaseChannelProtection {
    /**
     * deployment lifecycle options
     */
    deployment?: pulumi.Input<inputs.ReleaseChannelProtectionDeployment>;
    /**
     * name of the protection
     */
    name?: pulumi.Input<string>;
    /**
     * post-approval lifecycle options
     */
    postApproval?: pulumi.Input<inputs.ReleaseChannelProtectionPostApproval>;
    /**
     * post-deployment lifecycle options
     */
    postDeployment?: pulumi.Input<inputs.ReleaseChannelProtectionPostDeployment>;
    /**
     * pre-approval lifecycle options
     */
    preApproval?: pulumi.Input<inputs.ReleaseChannelProtectionPreApproval>;
    /**
     * reference to a protection stored in Prodvana
     */
    ref: pulumi.Input<inputs.ReleaseChannelProtectionRef>;
}

export interface ReleaseChannelProtectionDeployment {
    /**
     * whether to enable deployment lifecycle options
     */
    enabled?: pulumi.Input<boolean>;
}

export interface ReleaseChannelProtectionPostApproval {
    /**
     * whether to enable deployment lifecycle options
     */
    enabled?: pulumi.Input<boolean>;
}

export interface ReleaseChannelProtectionPostDeployment {
    /**
     * how long to keep checking. A valid Go duration string, e.g. `10m` or `1h`. Defaults to `10m`
     */
    checkDuration?: pulumi.Input<string>;
    /**
     * delay between the deployment completing and when this protection starts checking. A valid Go duration string, e.g. `10m` or `1h`. Defaults to `10m`
     */
    delayCheckDuration?: pulumi.Input<string>;
    /**
     * whether to enable deployment lifecycle options
     */
    enabled?: pulumi.Input<boolean>;
}

export interface ReleaseChannelProtectionPreApproval {
    /**
     * whether to enable deployment lifecycle options
     */
    enabled?: pulumi.Input<boolean>;
}

export interface ReleaseChannelProtectionRef {
    /**
     * name of the constant
     */
    name: pulumi.Input<string>;
    /**
     * parameters to pass to the protection
     */
    parameters?: pulumi.Input<pulumi.Input<inputs.ReleaseChannelProtectionRefParameter>[]>;
}

export interface ReleaseChannelProtectionRefParameter {
    /**
     * parameter docker image tag value, only one of (string*value, int*value, docker*image*tag*value, secret*value) can be set
     */
    dockerImageTagValue?: pulumi.Input<string>;
    /**
     * parameter int value, only one of (string*value, int*value, docker*image*tag*value, secret*value) can be set
     */
    intValue?: pulumi.Input<number>;
    /**
     * name of the constant
     */
    name: pulumi.Input<string>;
    /**
     * parameter secret value, only one of (string*value, int*value, docker*image*tag*value, secret*value) can be set
     */
    secretValue?: pulumi.Input<inputs.ReleaseChannelProtectionRefParameterSecretValue>;
    /**
     * string value of the constant
     */
    stringValue?: pulumi.Input<string>;
}

export interface ReleaseChannelProtectionRefParameterSecretValue {
    /**
     * Name of the secret.
     */
    key: pulumi.Input<string>;
    /**
     * Version of the secret
     */
    version: pulumi.Input<string>;
}

export interface ReleaseChannelReleaseChannelStablePrecondition {
    /**
     * name of a release channel that must be in a stable deployment state
     */
    releaseChannel: pulumi.Input<string>;
}

export interface ReleaseChannelRuntime {
    /**
     * Prefix used when naming ECS resources. Can only be set on an ECS Runtime.
     */
    ecsPrefix?: pulumi.Input<string>;
    /**
     * Optionally set a custom namespace. If not set, Prodvana will create and manage the namespace. If set, the namespace *must* already exist and Prodvana will not try to create or delete it. Can only be set on a Kubernetes Runtime.
     */
    k8sNamespace?: pulumi.Input<string>;
    /**
     * optional identifier for this runtime connection within this release channel
     */
    name?: pulumi.Input<string>;
    /**
     * name of the a runtime
     */
    runtime?: pulumi.Input<string>;
    /**
     * type of the runtime connection, one of (AWS*ECS, EXTENSION, GOOGLE*CLOUD*RUN, LONG*LIVED*COMPUTE, UNKNOWN*CONNECTION)
     */
    type?: pulumi.Input<string>;
}

export interface ReleaseChannelServiceInstanceProtection {
    /**
     * deployment lifecycle options
     */
    deployment?: pulumi.Input<inputs.ReleaseChannelServiceInstanceProtectionDeployment>;
    /**
     * name of the protection
     */
    name?: pulumi.Input<string>;
    /**
     * post-approval lifecycle options
     */
    postApproval?: pulumi.Input<inputs.ReleaseChannelServiceInstanceProtectionPostApproval>;
    /**
     * post-deployment lifecycle options
     */
    postDeployment?: pulumi.Input<inputs.ReleaseChannelServiceInstanceProtectionPostDeployment>;
    /**
     * pre-approval lifecycle options
     */
    preApproval?: pulumi.Input<inputs.ReleaseChannelServiceInstanceProtectionPreApproval>;
    /**
     * reference to a protection stored in Prodvana
     */
    ref: pulumi.Input<inputs.ReleaseChannelServiceInstanceProtectionRef>;
}

export interface ReleaseChannelServiceInstanceProtectionDeployment {
    /**
     * whether to enable deployment lifecycle options
     */
    enabled?: pulumi.Input<boolean>;
}

export interface ReleaseChannelServiceInstanceProtectionPostApproval {
    /**
     * whether to enable deployment lifecycle options
     */
    enabled?: pulumi.Input<boolean>;
}

export interface ReleaseChannelServiceInstanceProtectionPostDeployment {
    /**
     * how long to keep checking. A valid Go duration string, e.g. `10m` or `1h`. Defaults to `10m`
     */
    checkDuration?: pulumi.Input<string>;
    /**
     * delay between the deployment completing and when this protection starts checking. A valid Go duration string, e.g. `10m` or `1h`. Defaults to `10m`
     */
    delayCheckDuration?: pulumi.Input<string>;
    /**
     * whether to enable deployment lifecycle options
     */
    enabled?: pulumi.Input<boolean>;
}

export interface ReleaseChannelServiceInstanceProtectionPreApproval {
    /**
     * whether to enable deployment lifecycle options
     */
    enabled?: pulumi.Input<boolean>;
}

export interface ReleaseChannelServiceInstanceProtectionRef {
    /**
     * name of the constant
     */
    name: pulumi.Input<string>;
    /**
     * parameters to pass to the protection
     */
    parameters?: pulumi.Input<pulumi.Input<inputs.ReleaseChannelServiceInstanceProtectionRefParameter>[]>;
}

export interface ReleaseChannelServiceInstanceProtectionRefParameter {
    /**
     * parameter docker image tag value, only one of (string*value, int*value, docker*image*tag*value, secret*value) can be set
     */
    dockerImageTagValue?: pulumi.Input<string>;
    /**
     * parameter int value, only one of (string*value, int*value, docker*image*tag*value, secret*value) can be set
     */
    intValue?: pulumi.Input<number>;
    /**
     * name of the constant
     */
    name: pulumi.Input<string>;
    /**
     * parameter secret value, only one of (string*value, int*value, docker*image*tag*value, secret*value) can be set
     */
    secretValue?: pulumi.Input<inputs.ReleaseChannelServiceInstanceProtectionRefParameterSecretValue>;
    /**
     * string value of the constant
     */
    stringValue?: pulumi.Input<string>;
}

export interface ReleaseChannelServiceInstanceProtectionRefParameterSecretValue {
    /**
     * Name of the secret.
     */
    key: pulumi.Input<string>;
    /**
     * Version of the secret
     */
    version: pulumi.Input<string>;
}

export interface ReleaseChannelSharedManualApprovalPrecondition {
    /**
     * name of the manual approval
     */
    name?: pulumi.Input<string>;
}
