// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface GetReleaseChannelPolicy {
    /**
     * default environment variables for services in this Release Channel
     */
    defaultEnv: {[key: string]: outputs.GetReleaseChannelPolicyDefaultEnv};
}

export interface GetReleaseChannelPolicyDefaultEnv {
    secret?: outputs.GetReleaseChannelPolicyDefaultEnvSecret;
    value?: string;
}

export interface GetReleaseChannelPolicyDefaultEnvSecret {
    key?: string;
    /**
     * Current application version
     */
    version?: string;
}

export interface GetReleaseChannelRuntime {
    /**
     * ECS prefix
     */
    ecsPrefix: string;
    /**
     * Kubernetes namespace
     */
    k8sNamespace: string;
    /**
     * optional identifier for this runtime connection within this release channel
     */
    name: string;
    /**
     * name of the a runtime
     */
    runtime?: string;
    /**
     * type of the runtime connection, one of (EXTENSION, LONG*LIVED*COMPUTE, UNKNOWN_CONNECTION)
     */
    type: string;
}

export interface ManagedK8sRuntimeExec {
    /**
     * API version of the exec credential plugin
     */
    apiVersion: string;
    /**
     * Arguments to pass when executing the command
     */
    args?: string[];
    /**
     * Command to execute
     */
    command: string;
    /**
     * Environment variables to set when executing the command
     */
    env?: {[key: string]: string};
}

export interface ReleaseChannelPolicy {
    /**
     * default environment variables for services in this Release Channel
     */
    defaultEnv?: {[key: string]: outputs.ReleaseChannelPolicyDefaultEnv};
}

export interface ReleaseChannelPolicyDefaultEnv {
    secret?: outputs.ReleaseChannelPolicyDefaultEnvSecret;
    value?: string;
}

export interface ReleaseChannelPolicyDefaultEnvSecret {
    key?: string;
    /**
     * Current application version
     */
    version?: string;
}

export interface ReleaseChannelRuntime {
    /**
     * Prefix used when naming ECS resources. Can only be set on an ECS Runtime.
     */
    ecsPrefix: string;
    /**
     * Optionally set a custom namespace. If not set, Prodvana will create and manage the namespace. If set, the namespace *must* already exist and Prodvana will not try to create or delete it. Can only be set on a Kubernetes Runtime.
     */
    k8sNamespace: string;
    /**
     * optional identifier for this runtime connection within this release channel
     */
    name: string;
    /**
     * name of the a runtime
     */
    runtime?: string;
    /**
     * type of the runtime connection, one of (EXTENSION, LONG*LIVED*COMPUTE, UNKNOWN_CONNECTION)
     */
    type: string;
}

