// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Prodvana.Inputs
{

    public sealed class GetK8sRuntimeLabelArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Label name
        /// </summary>
        [Input("label", required: true)]
        public string Label { get; set; } = null!;

        /// <summary>
        /// Label value
        /// </summary>
        [Input("value", required: true)]
        public string Value { get; set; } = null!;

        public GetK8sRuntimeLabelArgs()
        {
        }
        public static new GetK8sRuntimeLabelArgs Empty => new GetK8sRuntimeLabelArgs();
    }
}
