// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Prodvana.Inputs
{

    public sealed class GetReleaseChannelServiceInstanceProtectionRefArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Release Channel name
        /// </summary>
        [Input("name", required: true)]
        public string Name { get; set; } = null!;

        [Input("parameters")]
        private List<Inputs.GetReleaseChannelServiceInstanceProtectionRefParameterArgs>? _parameters;
        public List<Inputs.GetReleaseChannelServiceInstanceProtectionRefParameterArgs> Parameters
        {
            get => _parameters ?? (_parameters = new List<Inputs.GetReleaseChannelServiceInstanceProtectionRefParameterArgs>());
            set => _parameters = value;
        }

        public GetReleaseChannelServiceInstanceProtectionRefArgs()
        {
        }
        public static new GetReleaseChannelServiceInstanceProtectionRefArgs Empty => new GetReleaseChannelServiceInstanceProtectionRefArgs();
    }
}
