// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Prodvana.Inputs
{

    public sealed class GetReleaseChannelPolicyDefaultEnvArgs : global::Pulumi.InvokeArgs
    {
        [Input("secret")]
        public Inputs.GetReleaseChannelPolicyDefaultEnvSecretArgs? Secret { get; set; }

        [Input("value")]
        public string? Value { get; set; }

        public GetReleaseChannelPolicyDefaultEnvArgs()
        {
        }
        public static new GetReleaseChannelPolicyDefaultEnvArgs Empty => new GetReleaseChannelPolicyDefaultEnvArgs();
    }
}
