// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Prodvana.Inputs
{

    public sealed class GetReleaseChannelServiceInstanceProtectionRefParameterArgs : global::Pulumi.InvokeArgs
    {
        [Input("dockerImageTagValue")]
        public string? DockerImageTagValue { get; set; }

        [Input("intValue")]
        public int? IntValue { get; set; }

        /// <summary>
        /// Release Channel name
        /// </summary>
        [Input("name", required: true)]
        public string Name { get; set; } = null!;

        [Input("secretValue")]
        public Inputs.GetReleaseChannelServiceInstanceProtectionRefParameterSecretValueArgs? SecretValue { get; set; }

        [Input("stringValue")]
        public string? StringValue { get; set; }

        public GetReleaseChannelServiceInstanceProtectionRefParameterArgs()
        {
        }
        public static new GetReleaseChannelServiceInstanceProtectionRefParameterArgs Empty => new GetReleaseChannelServiceInstanceProtectionRefParameterArgs();
    }
}
