// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Prodvana.Inputs
{

    public sealed class GetReleaseChannelPolicyArgs : global::Pulumi.InvokeArgs
    {
        [Input("defaultEnv", required: true)]
        private Dictionary<string, Inputs.GetReleaseChannelPolicyDefaultEnvArgs>? _defaultEnv;

        /// <summary>
        /// default environment variables for services in this Release Channel
        /// </summary>
        public Dictionary<string, Inputs.GetReleaseChannelPolicyDefaultEnvArgs> DefaultEnv
        {
            get => _defaultEnv ?? (_defaultEnv = new Dictionary<string, Inputs.GetReleaseChannelPolicyDefaultEnvArgs>());
            set => _defaultEnv = value;
        }

        public GetReleaseChannelPolicyArgs()
        {
        }
        public static new GetReleaseChannelPolicyArgs Empty => new GetReleaseChannelPolicyArgs();
    }
}
