// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Prodvana.Inputs
{

    public sealed class GetReleaseChannelReleaseChannelStablePreconditionArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// name of a release channel that must be in a stable deployment state
        /// </summary>
        [Input("releaseChannel", required: true)]
        public string ReleaseChannel { get; set; } = null!;

        public GetReleaseChannelReleaseChannelStablePreconditionArgs()
        {
        }
        public static new GetReleaseChannelReleaseChannelStablePreconditionArgs Empty => new GetReleaseChannelReleaseChannelStablePreconditionArgs();
    }
}
