// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Prodvana.Inputs
{

    public sealed class GetReleaseChannelProtectionDeploymentInputArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// whether to enable deployment lifecycle options
        /// </summary>
        [Input("enabled", required: true)]
        public Input<bool> Enabled { get; set; } = null!;

        public GetReleaseChannelProtectionDeploymentInputArgs()
        {
        }
        public static new GetReleaseChannelProtectionDeploymentInputArgs Empty => new GetReleaseChannelProtectionDeploymentInputArgs();
    }
}
