// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Prodvana.Inputs
{

    public sealed class GetReleaseChannelProtectionInputArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// deployment lifecycle options
        /// </summary>
        [Input("deployment")]
        public Input<Inputs.GetReleaseChannelProtectionDeploymentInputArgs>? Deployment { get; set; }

        /// <summary>
        /// name of the protection
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        /// <summary>
        /// post-approval lifecycle options
        /// </summary>
        [Input("postApproval")]
        public Input<Inputs.GetReleaseChannelProtectionPostApprovalInputArgs>? PostApproval { get; set; }

        /// <summary>
        /// post-deployment lifecycle options
        /// </summary>
        [Input("postDeployment")]
        public Input<Inputs.GetReleaseChannelProtectionPostDeploymentInputArgs>? PostDeployment { get; set; }

        /// <summary>
        /// pre-approval lifecycle options
        /// </summary>
        [Input("preApproval")]
        public Input<Inputs.GetReleaseChannelProtectionPreApprovalInputArgs>? PreApproval { get; set; }

        /// <summary>
        /// reference to a protection stored in Prodvana
        /// </summary>
        [Input("ref", required: true)]
        public Input<Inputs.GetReleaseChannelProtectionRefInputArgs> Ref { get; set; } = null!;

        public GetReleaseChannelProtectionInputArgs()
        {
        }
        public static new GetReleaseChannelProtectionInputArgs Empty => new GetReleaseChannelProtectionInputArgs();
    }
}
