// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Prodvana.Inputs
{

    public sealed class ManagedK8sRuntimeExecGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// API version of the exec credential plugin
        /// </summary>
        [Input("apiVersion", required: true)]
        public Input<string> ApiVersion { get; set; } = null!;

        [Input("args")]
        private InputList<string>? _args;

        /// <summary>
        /// Arguments to pass when executing the command
        /// </summary>
        public InputList<string> Args
        {
            get => _args ?? (_args = new InputList<string>());
            set => _args = value;
        }

        /// <summary>
        /// Command to execute
        /// </summary>
        [Input("command", required: true)]
        public Input<string> Command { get; set; } = null!;

        [Input("env")]
        private InputMap<string>? _env;

        /// <summary>
        /// Environment variables to set when executing the command
        /// </summary>
        public InputMap<string> Env
        {
            get => _env ?? (_env = new InputMap<string>());
            set => _env = value;
        }

        public ManagedK8sRuntimeExecGetArgs()
        {
        }
        public static new ManagedK8sRuntimeExecGetArgs Empty => new ManagedK8sRuntimeExecGetArgs();
    }
}
