// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Prodvana.Inputs
{

    public sealed class ReleaseChannelPolicyDefaultEnvSecretArgs : global::Pulumi.ResourceArgs
    {
        [Input("key")]
        public Input<string>? Key { get; set; }

        /// <summary>
        /// Current application version
        /// </summary>
        [Input("version")]
        public Input<string>? Version { get; set; }

        public ReleaseChannelPolicyDefaultEnvSecretArgs()
        {
        }
        public static new ReleaseChannelPolicyDefaultEnvSecretArgs Empty => new ReleaseChannelPolicyDefaultEnvSecretArgs();
    }
}
