// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Prodvana.Inputs
{

    public sealed class ReleaseChannelReleaseChannelStablePreconditionArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// name of a release channel that must be in a stable deployment state
        /// </summary>
        [Input("releaseChannel", required: true)]
        public Input<string> ReleaseChannel { get; set; } = null!;

        public ReleaseChannelReleaseChannelStablePreconditionArgs()
        {
        }
        public static new ReleaseChannelReleaseChannelStablePreconditionArgs Empty => new ReleaseChannelReleaseChannelStablePreconditionArgs();
    }
}
