// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Prodvana.Inputs
{

    public sealed class ReleaseChannelServiceInstanceProtectionGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// deployment lifecycle options
        /// </summary>
        [Input("deployment")]
        public Input<Inputs.ReleaseChannelServiceInstanceProtectionDeploymentGetArgs>? Deployment { get; set; }

        /// <summary>
        /// name of the protection
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// post-approval lifecycle options
        /// </summary>
        [Input("postApproval")]
        public Input<Inputs.ReleaseChannelServiceInstanceProtectionPostApprovalGetArgs>? PostApproval { get; set; }

        /// <summary>
        /// post-deployment lifecycle options
        /// </summary>
        [Input("postDeployment")]
        public Input<Inputs.ReleaseChannelServiceInstanceProtectionPostDeploymentGetArgs>? PostDeployment { get; set; }

        /// <summary>
        /// pre-approval lifecycle options
        /// </summary>
        [Input("preApproval")]
        public Input<Inputs.ReleaseChannelServiceInstanceProtectionPreApprovalGetArgs>? PreApproval { get; set; }

        /// <summary>
        /// reference to a protection stored in Prodvana
        /// </summary>
        [Input("ref", required: true)]
        public Input<Inputs.ReleaseChannelServiceInstanceProtectionRefGetArgs> Ref { get; set; } = null!;

        public ReleaseChannelServiceInstanceProtectionGetArgs()
        {
        }
        public static new ReleaseChannelServiceInstanceProtectionGetArgs Empty => new ReleaseChannelServiceInstanceProtectionGetArgs();
    }
}
