// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Prodvana.Inputs
{

    public sealed class ReleaseChannelConstantArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// name of the constant
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        /// <summary>
        /// string value of the constant
        /// </summary>
        [Input("stringValue", required: true)]
        public Input<string> StringValue { get; set; } = null!;

        public ReleaseChannelConstantArgs()
        {
        }
        public static new ReleaseChannelConstantArgs Empty => new ReleaseChannelConstantArgs();
    }
}
