// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Prodvana.Inputs
{

    public sealed class ReleaseChannelSharedManualApprovalPreconditionArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// name of the manual approval
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        public ReleaseChannelSharedManualApprovalPreconditionArgs()
        {
        }
        public static new ReleaseChannelSharedManualApprovalPreconditionArgs Empty => new ReleaseChannelSharedManualApprovalPreconditionArgs();
    }
}
