// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Prodvana.Inputs
{

    public sealed class ReleaseChannelProtectionRefParameterGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// parameter docker image tag value, only one of (string*value, int*value, docker*image*tag*value, secret*value) can be set
        /// </summary>
        [Input("dockerImageTagValue")]
        public Input<string>? DockerImageTagValue { get; set; }

        /// <summary>
        /// parameter int value, only one of (string*value, int*value, docker*image*tag*value, secret*value) can be set
        /// </summary>
        [Input("intValue")]
        public Input<int>? IntValue { get; set; }

        /// <summary>
        /// name of the constant
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        /// <summary>
        /// parameter secret value, only one of (string*value, int*value, docker*image*tag*value, secret*value) can be set
        /// </summary>
        [Input("secretValue")]
        public Input<Inputs.ReleaseChannelProtectionRefParameterSecretValueGetArgs>? SecretValue { get; set; }

        /// <summary>
        /// string value of the constant
        /// </summary>
        [Input("stringValue")]
        public Input<string>? StringValue { get; set; }

        public ReleaseChannelProtectionRefParameterGetArgs()
        {
        }
        public static new ReleaseChannelProtectionRefParameterGetArgs Empty => new ReleaseChannelProtectionRefParameterGetArgs();
    }
}
