// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Prodvana.Inputs
{

    public sealed class ReleaseChannelServiceInstanceProtectionRefArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Release Channel name
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        [Input("parameters")]
        private InputList<Inputs.ReleaseChannelServiceInstanceProtectionRefParameterArgs>? _parameters;
        public InputList<Inputs.ReleaseChannelServiceInstanceProtectionRefParameterArgs> Parameters
        {
            get => _parameters ?? (_parameters = new InputList<Inputs.ReleaseChannelServiceInstanceProtectionRefParameterArgs>());
            set => _parameters = value;
        }

        public ReleaseChannelServiceInstanceProtectionRefArgs()
        {
        }
        public static new ReleaseChannelServiceInstanceProtectionRefArgs Empty => new ReleaseChannelServiceInstanceProtectionRefArgs();
    }
}
