// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Prodvana.Inputs
{

    public sealed class ReleaseChannelPolicyArgs : global::Pulumi.ResourceArgs
    {
        [Input("defaultEnv")]
        private InputMap<Inputs.ReleaseChannelPolicyDefaultEnvArgs>? _defaultEnv;

        /// <summary>
        /// default environment variables for services in this Release Channel
        /// </summary>
        public InputMap<Inputs.ReleaseChannelPolicyDefaultEnvArgs> DefaultEnv
        {
            get => _defaultEnv ?? (_defaultEnv = new InputMap<Inputs.ReleaseChannelPolicyDefaultEnvArgs>());
            set => _defaultEnv = value;
        }

        public ReleaseChannelPolicyArgs()
        {
        }
        public static new ReleaseChannelPolicyArgs Empty => new ReleaseChannelPolicyArgs();
    }
}
