// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Prodvana.Inputs
{

    public sealed class ReleaseChannelPolicyDefaultEnvGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("kubernetesSecret")]
        public Input<Inputs.ReleaseChannelPolicyDefaultEnvKubernetesSecretGetArgs>? KubernetesSecret { get; set; }

        [Input("secret")]
        public Input<Inputs.ReleaseChannelPolicyDefaultEnvSecretGetArgs>? Secret { get; set; }

        [Input("value")]
        public Input<string>? Value { get; set; }

        public ReleaseChannelPolicyDefaultEnvGetArgs()
        {
        }
        public static new ReleaseChannelPolicyDefaultEnvGetArgs Empty => new ReleaseChannelPolicyDefaultEnvGetArgs();
    }
}
