// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Prodvana Kubernetes Runtime
 */
export function getK8sRuntime(args: GetK8sRuntimeArgs, opts?: pulumi.InvokeOptions): Promise<GetK8sRuntimeResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("prodvana:index/getK8sRuntime:getK8sRuntime", {
        "labels": args.labels,
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getK8sRuntime.
 */
export interface GetK8sRuntimeArgs {
    /**
     * List of labels to apply to the runtime
     */
    labels?: inputs.GetK8sRuntimeLabel[];
    /**
     * Runtime name
     */
    name: string;
}

/**
 * A collection of values returned by getK8sRuntime.
 */
export interface GetK8sRuntimeResult {
    /**
     * API Token used for linking the Kubernetes Prodvana agent
     */
    readonly agentApiToken: string;
    /**
     * Runtime identifier
     */
    readonly id: string;
    /**
     * List of labels to apply to the runtime
     */
    readonly labels: outputs.GetK8sRuntimeLabel[];
    /**
     * Runtime name
     */
    readonly name: string;
}
/**
 * Prodvana Kubernetes Runtime
 */
export function getK8sRuntimeOutput(args: GetK8sRuntimeOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetK8sRuntimeResult> {
    return pulumi.output(args).apply((a: any) => getK8sRuntime(a, opts))
}

/**
 * A collection of arguments for invoking getK8sRuntime.
 */
export interface GetK8sRuntimeOutputArgs {
    /**
     * List of labels to apply to the runtime
     */
    labels?: pulumi.Input<pulumi.Input<inputs.GetK8sRuntimeLabelArgs>[]>;
    /**
     * Runtime name
     */
    name: pulumi.Input<string>;
}
